var links =[{
  "id": 1,
  "link": "https://fastcompany.com/donec/quis",
  "danger": 2,
  "origin": "Portugal"
}, {
  "id": 2,
  "link": "http://fotki.com/ultrices/enim",
  "danger": 2,
  "origin": "Iraq"
}, {
  "id": 3,
  "link": "http://ehow.com/donec.html?",
  "danger": 1,
  "origin": "Palestinian Territory"
}, {
  "id": 4,
  "link": "https://diigo.com/aenean/fermentum/",
  "danger": 3,
  "origin": "Kenya"
}, {
  "id": 5,
  "link": "http://diigo.com/fermentum/donec/",
  "danger": 1,
  "origin": "Russia"
}, {
  "id": 6,
  "link": "https://hubpages.com/parturient/montes",
  "danger": 2,
  "origin": "Saudi Arabia"
}, {
  "id": 7,
  "link": "http://cnet.com/enim/leo/rhoncus/sed/", "danger": 3,
  "origin": "Russia"
}, {
  "id": 8,
  "link": "http://jigsy.com/parturient/montes/",
  "danger": 2,
  "origin": "Indonesia"
}, {
  "id": 9,
  "link": "https://chicagotribune.com/",
  "danger": 3,
  "origin": "Brazil"
}, {
  "id": 10,
  "link": "https://ucoz.ru/in/hac/habitasse/",
   "danger": 1,
  "origin": "Russia"
}, {
  "id": 11,
  "link": "http://123-reg.co.uk/erat/quisque/erat",
  "danger": 1,
  "origin": "Croatia"
}, {
  "id": 12,
  "link": "https://yale.edu/duis/bibendume",
  "danger": 3,
  "origin": "Brazil"
}, {
  "id": 13,
  "link": "http://ezinearticles.com/ut/",
  "danger": 3,
  "origin": "United States"
}, {
  "id": 14,
  "link": "http://cocolog-nifty.com/",
  "danger": 2,
  "origin": "Bosnia and Herzegovina"
}, {
  "id": 15,
  "link": "http://desdev.cn/blandit/nam",
  "danger": 2,
  "origin": "China"
}, {
  "id": 16,
  "link": "http://sfgate.com/pulvinar/lobortis"
  ,"danger": 1,
  "origin": "Nepal"
}, {
  "id": 17,
  "link": "https://java.com/tristique/est/",
  "danger": 3,
  "origin": "Estonia"
}, {
  "id": 18,
  "link": "https://meetup.com/varius/ut/blandit/",
  "danger": 2,
  "origin": "Brazil"
}, {
  "id": 19,
  "link": "https://trellian.com/congue/risus/"
  ,"danger": 2,
  "origin": "Norway"
}, {
  "id": 20,
  "link": "https://nhs.uk/quis/turpis/sed.png?m",
  "danger": 2,
  "origin": "Honduras"
}];

export {links};
